name: Hourly Render Ping

on:
  schedule:
      - cron: '*/2 * * * *'  # Runs every 14 minutes
  workflow_dispatch:      # Allows manual triggering

jobs:
  ping-websites:
    runs-on: ubuntu-latest

    steps:
      - name: Ping websites using cURL
        run: |
          curl -I https://veri-scan.onrender.com
